routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

use App\Http\Controllers\Admin\AdminCategoryController;
use App\Http\Controllers\Admin\AdminProductController;
use App\Http\Controllers\Admin\AdminEmpController;
use App\Http\Controllers\Emp\EmpCategoryController;
use App\Http\Controllers\Emp\EmpProductController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/demo', [AdminProductController::class, 'demo']); //Product Resource

Route::get('/', function () {
    return view('welcome');
});

Route::middleware(['middleware'=>'preventBackHistroy'])->group(function () {
    Auth::routes();
});


 /* Admin Route Group */
Route::group(['prefix'=>'admin', 'middleware'=>['isAdmin','auth','preventBackHistroy']], function(){

    Route::get('/adminhome', [App\Http\Controllers\HomeController::class, 'admin'])->name('admin.home'); // Admin Home

    Route::resource('adminemp',AdminEmpController::class); //Employee CRUD Resource

    Route::resource('adminproduct',AdminProductController::class); //Product Resource

    Route::resource('admincategory',AdminCategoryController::class); //Category Resoure

    Route::get('/export', [AdminProductController::class, 'export'])->name('adminproduct.export');
    Route::get('/import-form', [AdminProductController::class, 'importform'])->name('adminproduct.import-form');
    Route::post('/import', [AdminProductController::class, 'import'])->name('adminproduct.import');
    Route::get('/sample-excel', [AdminProductController::class, 'sample_excel']);


});

 /* Employee Route Group */
Route::group(['prefix'=>'emp', 'middleware'=>['isEmp','auth','preventBackHistroy']], function(){

    Route::get('/emphome', [App\Http\Controllers\HomeController::class, 'emp'])->name('emp.home'); // Employee Home

    Route::resource('empproduct',EmpProductController::class); //Product Resource

    Route::resource('empcategory',EmpCategoryController::class); //Category Resoure

    // Import and Export
    Route::get('/export', [EmpProductController::class, 'export'])->name('empproduct.export');
    Route::get('/import-form', [EmpProductController::class, 'importform'])->name('empproduct.import-form');
    Route::post('/import', [EmpProductController::class, 'import'])->name('empproduct.import');
    Route::get('/sample-excel', [EmpProductController::class, 'sample_excel']);


});

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Category extends Model
{
    use HasFactory, SoftDeletes;

    // protected $connection = 'mysql_madurai';
    public function changeConnection($conn)
    {
        $this->connection = $conn;
    }

    protected $table = 'categories';

    protected $fillable = [
        'categoryname',
    ];

    // connect to product table using many to many relationship
    public function products()
    {
        return $this->belongsToMany(Product::class, 'category_product');
    }
}

resources/views/dashboard/admin/category/add.blade.php
@extends('layouts.app')

@section('content')

<div class="container justify-contant-center">
    <div class="col-md-6">
        <div class="card">
            <div class="card-header">Add Your Category</div>

            @if (Session::get('error'))
                <div class="alert alert-danger">{{ Session::get('error') }}</div>
            @endif

            <div class="card-body">
                <form action="{{ route('admincategory.store') }}" method="post">
                    @csrf
                    @method('post')
                    <div class="form-group">
                        <label>Category Name</label>
                        <input type="text" name="categoryname" class="form-control" value="{{ old('categoryname') }}">
                        <span class="text-danger">@error('categoryname'){{ $message }}@enderror</span>
                    </div>
                    <button type="submit" class="btn btn-success">Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>



@endsection

resources/views/dashboard/admin/category/edit.blade.php
@extends('layouts.app')

@section('content')

<div class="container justify-contant-center">
    <div class="col-md-6">
        <div class="card">
            <div class="card-header">Update Your Category</div>

            @if (Session::get('error'))
                <div class="alert alert-danger">{{ Session::get('error') }}</div>
            @endif

            <div class="card-body">
                <form action="{{ route('admincategory.update' , ['admincategory' => $category->id]) }}" method="post">
                    @csrf
                    @method('patch')
                    <div class="form-group">
                        <label>Category Id</label>
                        <input type="text" name="id" class="form-control" disabled value="{{ $category->id }}">
                    </div>
                    <div class="form-group">
                        <label>Category Name</label>
                        <input type="text" name="categoryname" class="form-control" value="{{ $category->categoryname }}">
                        <span class="text-danger">@error('categoryname'){{ $message }}@enderror</span>
                    </div>

                    <button type="submit" class="btn btn-success">Update</button>
                </form>

            </div>
        </div>
    </div>
</div>



@endsection

resources/views/dashboard/admin/category/home.blade.php
@extends('layouts.app')


@section('content')

<div class="container">
    <div class="float-right my-3">
        <a href="{{ route('admincategory.create') }}" class="btn btn-primary">Add Category</a>
    </div>
    <div class="table-responsive">
        @if (Session::get('success'))
        <div class="alert alert-success">{{ Session::get('success') }}</div>
        @endif
        <table class="table table-bordered text-center">
            <thead>
                <tr>
                    <th>Sno</th>
                    <th>Category Name</th>
                    <th colspan="2">Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($categorys as $category)
                    <tr>
                        <td>{{ $category->id }}</td>
                        <td>{{ $category->categoryname }}</td>
                        <td>
                            <a href="{{ route('admincategory.edit',['admincategory' => $category->id]) }}" class="btn btn-success">Edit</a>
                            <form hidden action="{{ '/admin/admincategory/'.$category->id }}" class="d-inline" method="post" onsubmit="return confirm('Are you delete the category ?')">
                                @csrf
                                @method('delete')
                                <button type="submit" class="btn btn-danger">Delete</button>
                            </form>
                        </td>
                    </tr>

                @endforeach
            </tbody>
        </table>
    </div>
</div>




@endsection