routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

use App\Http\Controllers\Admin\AdminCategoryController;
use App\Http\Controllers\Admin\AdminProductController;
use App\Http\Controllers\Admin\AdminEmpController;
use App\Http\Controllers\Emp\EmpCategoryController;
use App\Http\Controllers\Emp\EmpProductController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/demo', [AdminProductController::class, 'demo']); //Product Resource

Route::get('/', function () {
    return view('welcome');
});

Route::middleware(['middleware'=>'preventBackHistroy'])->group(function () {
    Auth::routes();
});


 /* Admin Route Group */
Route::group(['prefix'=>'admin', 'middleware'=>['isAdmin','auth','preventBackHistroy']], function(){

    Route::get('/adminhome', [App\Http\Controllers\HomeController::class, 'admin'])->name('admin.home'); // Admin Home

    Route::resource('adminemp',AdminEmpController::class); //Employee CRUD Resource

    Route::resource('adminproduct',AdminProductController::class); //Product Resource

    Route::resource('admincategory',AdminCategoryController::class); //Category Resoure

    Route::get('/export', [AdminProductController::class, 'export'])->name('adminproduct.export');
    Route::get('/import-form', [AdminProductController::class, 'importform'])->name('adminproduct.import-form');
    Route::post('/import', [AdminProductController::class, 'import'])->name('adminproduct.import');
    Route::get('/sample-excel', [AdminProductController::class, 'sample_excel']);


});

 /* Employee Route Group */
Route::group(['prefix'=>'emp', 'middleware'=>['isEmp','auth','preventBackHistroy']], function(){

    Route::get('/emphome', [App\Http\Controllers\HomeController::class, 'emp'])->name('emp.home'); // Employee Home

    Route::resource('empproduct',EmpProductController::class); //Product Resource

    Route::resource('empcategory',EmpCategoryController::class); //Category Resoure

    // Import and Export
    Route::get('/export', [EmpProductController::class, 'export'])->name('empproduct.export');
    Route::get('/import-form', [EmpProductController::class, 'importform'])->name('empproduct.import-form');
    Route::post('/import', [EmpProductController::class, 'import'])->name('empproduct.import');
    Route::get('/sample-excel', [EmpProductController::class, 'sample_excel']);


});

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\DB;

class Product extends Model
{
    use HasFactory,SoftDeletes;

    protected $connection = 'mysql_dindigul';
    // public function getConnection()
    // {
    //     $this->connection = 'mysql_dindigul';
    // }

    protected $fillable = [
        'productname',
        'description',
        'amount',
        'productcode',
    ];

    // Connect to Categories table using Many to Many- relationship
    public function categories()
    {
        return $this->belongsToMany(Category::class, 'category_product');
    }

    public static function getProduct()
    {
        $product = DB::connection('mysql_madurai')->select('select products.productcode, products.productname,products.description ,products.amount, categories.categoryname
        from products INNER JOIN categories on products.id=categories.id');
        return $product;
    }
}

resources/views/dashboard/employee/product/add.blade.php
@extends('layouts.app')

@section('content')

<div class="container justify-contant-center">
    <div class="col-md-6">
        <div class="card">
            <div class="card-header">Add Your Product</div>

            @if (Session::get('error'))
                <div class="alert alert-danger">{{ Session::get('error') }}</div>
            @endif

            <div class="card-body">
                <form action="{{ route('empproduct.store') }}" method="post">
                    @csrf
                    @method('post')
                    <div class="form-group">
                        <label>Product Name</label><span class="text-danger">*</span>
                        <input type="text" name="productname" class="form-control" value="{{ old('productname') }}">
                        <span class="text-danger">@error('productname'){{ $message }}@enderror</span>
                    </div>
                    <div class="form-group">
                        <label>Product Code</label><span class="text-danger">*</span>
                        <input type="text" name="productcode" class="form-control" value="{{ old('productcode') }}">
                        <span class="text-danger">@error('productcode'){{ $message }}@enderror</span>
                    </div>
                    <div class="form-group">
                        <label>Product Description</label><span class="text-danger">*</span>
                        <input type="text" name="description" class="form-control" value="{{ old('description') }}">
                        <span class="text-danger">@error('description'){{ $message }}@enderror</span>
                    </div>
                    <div class="form-group">
                        <label>Amount</label><span class="text-danger">*</span>
                        <input type="text" name="amount" class="form-control" value="{{ old('amount') }}">
                        <span class="text-danger">@error('amount'){{ $message }}@enderror</span>
                    </div>
                    <div class="form-group">
                        <label>Category</label><span class="text-danger">*</span>
                        <select name="category" class="form-control">
                            @foreach ($categorys as $category)
                            <option value="{{ $category->id }}">{{ $category->categoryname }}</option>
                            @endforeach
                        </select>
                        <span class="text-danger">@error('category'){{ $message }}@enderror</span>
                    </div>

                    <button type="submit" class="btn btn-success">Submit</button>
                </form>

            </div>
        </div>
    </div>
</div>



@endsection

resources/views/dashboard/employee/product/edit.blade.php
@extends('layouts.app')

@section('content')

<div class="container justify-contant-center">
    <div class="col-md-6">
        <div class="card">
            <div class="card-header">Update Your Product</div>

            @if (Session::get('error'))
                <div class="alert alert-danger">{{ Session::get('error') }}</div>
            @endif

            <div class="card-body">
                <form action="{{  '/emp/empproduct/'.$product->id }}" method="post">
                    @csrf
                    @method('patch')
                    <div class="form-group">
                        <label>Product Id</label><span class="text-danger">*</span>
                        <input type="text" name="productname" class="form-control" disabled value="{{ $product->id }}">
                    </div>
                    <div class="form-group">
                        <label>Product Name</label><span class="text-danger">*</span>
                        <input type="text" name="productname" class="form-control" value="{{ $product->productname }}">
                        <span class="text-danger">@error('productname'){{ $message }}@enderror</span>
                    </div>
                    <div class="form-group">
                        <label>Product Code</label><span class="text-danger">*</span>
                        <input type="text" name="productcode" class="form-control" value="{{ $product->productcode }}">
                        <span class="text-danger">@error('productcode'){{ $message }}@enderror</span>
                    </div>
                    <div class="form-group">
                        <label>Product Description</label><span class="text-danger">*</span>
                        <input type="text" name="description" class="form-control" value="{{ $product->description }}">
                        <span class="text-danger">@error('description'){{ $message }}@enderror</span>
                    </div>
                    <div class="form-group">
                        <label>Amount</label><span class="text-danger">*</span>
                        <input type="text" name="amount" class="form-control" value="{{ $product->amount }}">
                        <span class="text-danger">@error('amount'){{ $message }}@enderror</span>
                    </div>
                    <div class="form-group">
                        <label>Category</label><span class="text-danger">*</span>
                        <select name="category" class="form-control">
                            @foreach ($category as $category)
                            <option value="{{ $category->id }}">{{ $category->categoryname }}</option>
                            @endforeach
                        </select>
                        <span class="text-danger">@error('category'){{ $message }}@enderror</span>
                    </div>

                    <button type="submit" class="btn btn-success">Update</button>
                </form>

            </div>
        </div>
    </div>
</div>



@endsection

resources/views/dashboard/employee/product/home.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">

        <div class="row table-responsive ">
            <div class="col-md-12">

                <div class="float-left">
                    <a href="{{ route('empproduct.export') }}" class="btn btn-success mr-3">Export</a>
                </div>
                <div class="float-left">
                    <a href="{{ route('empproduct.import-form') }}" class="btn btn-primary">Import</a>
                </div>

                <div class="float-right">
                    <span>Total </span>
                    <img src="{{ asset('image/product_image.png') }}" width="45px"><span class="span"></span>
                </div>
                <div class="float-right">
                    <a href="{{ route('empproduct.create') }}" class="btn btn-primary mr-3">Add Product</a>
                </div>
            </div>
        </div>

        <div class="row mt-3">
            <div class="table-responsive ">
                @if (Session::get('success'))
                <div class="alert alert-success">{{ Session::get('success') }}</div>
                @endif
                <table id="productTbl" class="table table-bordered data-table" style="width:100%">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Product Code</th>
                            <th>Product Name</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            </div>
        </div>

    </div>
@endsection

{{-- Javascript --}}
@push('javascript')

    <script type="text/javascript">
    //  Yajra DataTable Script
        $(function () {
            var table = $('.data-table').DataTable({
                processing: true,
                serverSide: true,
                ajax: "{{ route('empproduct.index') }}",
                columns: [
                    {data: 'id', name: 'id'},
                    {data: 'productcode', name: 'productcode'},
                    {data: 'productname', name: 'productname'},
                    {data: 'action', name: 'action', orderable: false, searchable: false},
                ]
            });

        });

    // Firebase Real Time Live Product Count
    var starCountRef = firebase.database().ref('productcount/count');

        starCountRef.on('value', (snapshot) => {
        const data = snapshot.val();
        document.getElementsByClassName('span')[0].innerHTML = data;

    });
    </script>

@endpush

resources/views/dashboard/employee/product/import.blade.php
@extends('layouts.app')

@section('content')



<div class="container">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <div class="card">
                <div class="card-header">Import Product Form excel</div>
                <div class="card-body">
                    <form action="{{ route('empproduct.import') }}" method="post" enctype="multipart/form-data">
                        @csrf
                        <div class="form-group">
                            <label>Choose Excel file</label><span class="text-danger">*</span>
                            <input type="file" name="file" class="form-control" >
                            <span class="text-danger">@error('file'){{ $message }}@enderror</span>
                        </div>
                        <button type="submit" class="btn btn-primary">Upload</button>
                    </form>
                    <p>You can also sample file <a href="/emp/sample-excel">Here</a></p>
                </div>
            </div>
        </div>
    </div>
</div>


@endsection

resources/views/dashboard/employee/product/view.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">View Product Details</div>
            <div class="card-body">

                <div class="row md-3">
                    <div class="col-md-3">
                        <label class="my-3"><b>Product Code</b></label>
                    </div>
                    <div class="col-md-8">
                    <label class="my-3">{{ $products[0]->productcode }}</label>
                    </div>
                </div>

                <div class="row md-3">
                    <div class="col-md-3">
                        <label class="my-3"><b>Category</b></label>
                    </div>
                    <div class="col-md-8">
                    <label class="my-3">{{ $products[0]->categoryname }}</label>
                    </div>
                </div>

                <div class="row md-3">
                    <div class="col-md-3">
                        <label class="my-3"><b>Product Name</b></label>
                    </div>
                    <div class="col-md-8">
                    <label class="my-3">{{ $products[0]->productname }}</label>
                    </div>
                </div>

                <div class="row md-3">
                    <div class="col-md-3">
                        <label class="my-3"><b>Description</b></label>
                    </div>
                    <div class="col-md-8">
                    <label class="my-3">{{ $products[0]->description }}</label>
                    </div>
                </div>


                <div class="row md-3">
                    <div class="col-md-3">
                        <label class="my-3"><b>Amount</b></label>
                    </div>
                    <div class="col-md-8">
                    <label class="my-3">{{ $products[0]->amount }}</label>
                    </div>
                </div>

                <a href="{{ route('empproduct.index') }}" class="btn btn-primary">Back</a>
            </div>
        </div>
    </div>
</div>


@endsection